### ISSUE TITLE
Replacer not used in the first run

### ISSUE THREAD

**Issue by buildersteven4** [WebReflection/flatted#77] opened 2024-04-17 21:09 UTC
Stringify doesn't use the replacer function during the first run. Causing it to stringify objects before I get to replace them.

In my specific case I have objects that contain some Luxon DateTimes. These get converted to strings before the replacer function can touch them.

(At least, I think that is happening)

**Comment by WebReflection** [comment] 2024-04-18 12:09
code coverage and tests beg to differ ... add 154 million monthly downloads to the equation so unless you provide me a really convincing minimal example I can reproduce your issue with, I am afraid no action will be taken.

This project is done and stable, every change will have a *YAGNI* approach because of the amount of dependent projects that trust its robustness and performance that won't likely change ever, specially with breaking change suggestions such as yours.

I am all in to fix bugs but what you are saying doesn't feel or look right to me as many others would've noticed already ... still happy to have a look at any minimal reproducible code that doesn't use 3rd party indirections at all, thanks!

**Comment by WebReflection** [comment] 2024-06-24 05:56
Closing as nothing happened since April.

**Closed by WebReflection** 2024-06-24 05:56 UTC
Labels: invalid
